
[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.7
[window.padding]
x = 15
y = 15

[general]

live_config_reload = true
import = ["~/.config/alacritty/rice-colors.toml", "~/.config/alacritty/fonts.toml"]
